#!/bin/bash

source "$(pwd)/scripts/move_configs_h.sh"

DOTFILES_DIR="$(pwd)/dotfiles"

# enable matching hidden files (except . and ..)
shopt -s dotglob

echo "Starting dotfiles installation..."
echo "Copying files from $DOTFILES_DIR to $HOME"

for file in "$DOTFILES_DIR"/*; do
    [[ "$file" =~ /\.git$ ]] && continue
    
    filename="$(basename "$file")"
    target="$HOME/$filename"
    
    echo "Processing $filename..."
    
    # Backup existing file
    if ! backup_file "$target"; then
        echo "Warning: Failed to backup $target" >&2
        continue
    fi
     
    rm -rf "$target" 
    ln -s "$file" "$target"
    # cp -r "$file" "$HOME/"
    
    echo "Copied $filename to $HOME"
done

EXPORTS_FILE="$HOME/.zsh_exports_temp"

if [[ -f "$EXPORTS_FILE" ]]; then
    echo "Processing zsh exports..."
    
    if ! grep -q "### AUTOGENERATED EXPORTS ###" "$HOME/.zshrc"; then
        {
            echo ""
            echo "### AUTOGENERATED EXPORTS ###"
            cat "$EXPORTS_FILE"
        } >> "$HOME/.zshrc"
        echo "Added exports to .zshrc"
    else
        echo "Exports already present in .zshrc"
    fi
    
    # Uncomment after testing
    # rm "$EXPORTS_FILE"
fi

echo "Dotfiles installation complete!"
